# behat.yml
default:
  autoload:
    '': features/bootstrap
  extensions:
    Behat\MinkExtension:
      base_url:  'http://localhost:8000'
      goutte: ~
  suites:
    default:
      paths:
        - features
